clone:
  depth: full
  lfs: true

CommonScript: &CommonScript
  script:
    - export REACT_APP_API_ADDRESS=$API_ADDRESS
    - export REACT_APP_API_VERSION=$API_VERSION
    - npm install
    - npm run build
    - chmod 755 ./build
    - find ./build -type d -exec chmod 755 {} \;
    - find ./build -type f -exec chmod 644 {} \;
    - apt-get update && apt-get install -y unzip rsync
    - rsync -rpvz --delete build/ $SERVER_USER@$SERVER_ADDRESS:/home/$SERVER_USER/frontend
    - ssh $SERVER_USER@$SERVER_ADDRESS "sudo -u www-data rsync -rpvz --delete /home/$SERVER_USER/frontend/ $SERVER_DEPLOY_PATH"
    - echo "Production Version Deployed"

# Reusable steps code (by using the '<<: *step-name' operator below)
deploy-to-staging-server-step: &deploy-to-staging-server-step
  - step:
        name: Deploy to staging server
        image: node:14.1.0
        caches:
          - node
        - <<: *CommonScript

# Reusable steps code (by using the '<<: *step-name' operator below)
deploy-to-production-server-step: &deploy-to-production-server-step
  - step:
        name: Deploy to production server
        deployment: production
        image: node:14.1.0
        caches:
          - node
        - <<: *CommonScript

pipelines:
  custom:
    staging-manual-deploy:
      - <<: *deploy-to-staging-server-step
  branches:
    staging:
      - <<: *deploy-to-staging-server-step
    master:
      - <<: *deploy-to-production-server-step